In [20]:
import numpy as np
#Use the following code for the questions below:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [21]:
#1. How many negative numbers are there?
len(a[a<0])

4

In [22]:
#2. How many positive numbers are there?
len(a[a>0])

5

In [23]:
#3. How many even positive numbers are there?
b = a[a>0]
c = b % 2 == 0
b[c]
len (b[c])

3

In [24]:
#4. if you were to add 3 to each data point, how many positive numbers would there be?
d = a+3
e = d[d % 2 == 0]
e


array([26,  2,  6, -4])

In [25]:
len (e[e > 0 ])

3

In [26]:
#5. If you squared each number, what would the new mean and standard deviation be?
import math
squared_array = a ** 2
squared_array

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [27]:
squared_array.mean(), squared_array.std()

(74.0, 144.0243035046516)

In [28]:
#6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set.
a.mean()

3.0

In [29]:
center_data = a - a.mean()
center_data

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [30]:
# lets check , mean has to be zero
center_data.mean()

0.0

In [35]:
#7. Calculate the z-score for each data point.
a.mean()
a.std()
z_score == (a - a.mean())/a.std()
z_score

AttributeError: 'list' object has no attribute 'mean'

In [40]:
# 8. Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.
import numpy as np
## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list
b = np.sum(a)
b

55

In [41]:
#  Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list
min_of_a = np.min(a)
min_of_a

1

In [42]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list
max_of_a = np.max(a)
max_of_a

10

In [43]:
#  Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

mean_of_a = np.mean(a)
mean_of_a

5.5

In [44]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together
product_of_a = np.product(a)
product_of_a

3628800

In [45]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]
square_of_a = np.square(a)
square_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [46]:
#  Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers
#convert list to array first
a = np.array(a)
odds_in_a = a[a % 2 == 1]

odds_in_a

array([1, 3, 5, 7, 9])

In [47]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.
evens_in_a = a[a % 2 == 0]
evens_in_a

array([ 2,  4,  6,  8, 10])

In [48]:
## ## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, pro

b = [
    [3, 4, 5],
    [6, 7, 8]
]
type(b)
b = np.array(b)
b

array([[3, 4, 5],
       [6, 7, 8]])

In [49]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
#sum_of_b = 0
#for row in b:
   # sum_of_b += sum(row)
    
sum_of_b = np.sum(b)
sum_of_b


33

In [50]:
# # Exercise 2 - refactor the following to use numpy. 
#min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])

min_of_b = np.min(b)
min_of_b

3

In [51]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
#max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

max_of_b = np.max(b)
max_of_b

8

In [52]:
# Exercise 4 - refactor the following using numpy to find the mean of b
#mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

mean_of_b = np.mean(c)
mean_of_b


0.6

In [53]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

product_of_b = np.product(b)
product_of_b

20160

In [54]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)
    
squares_of_b = np.square(b)
squares_of_b

array([[ 9, 16, 25],
       [36, 49, 64]])

In [55]:
# # Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)

odds_in_b = b[b % 2 != 0]
odds_in_b
        
        


array([3, 5, 7])

In [56]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
            
            
evens_in_b = b[b % 2 == 0]
evens_in_b

array([4, 6, 8])

In [57]:
# Exercise 9 - print out the shape of the array b.shape
np.shape(b)

(2, 3)

In [58]:
# Exercise 10 - transpose the array b.
np.transpose(b)

array([[3, 6],
       [4, 7],
       [5, 8]])

In [62]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)
b.reshape(1,6)

array([[3, 4, 5, 6, 7, 8]])

In [63]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)
b.reshape(6,1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [65]:
# ## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# HINT, you'll first need to make sure that the "c" variable is a numpy array prior 

In [66]:
c = np.array(c)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
# Exercise 1 - Find the min, max, sum, and product of c.
c.min(), c.max(), c.sum(), c.prod()

(1, 9, 45, 362880)

In [69]:
# Exercise 2 - Determine the standard deviation of c.
c.std()

2.581988897471611

In [72]:
# Exercise 3 - Determine the variance of c.
c.var()

6.666666666666667

In [73]:
# Exercise 4 - Print out the shape of the array c
c.shape

(3, 3)

In [74]:
# Exercise 5 - Transpose c and print out transposed result.
c.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [79]:
# Exercise 6 - Get the dot product of the array c with c. 
c.dot(c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [81]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261
np.sum(c * np.transpose(c))

261

In [82]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.
np.prod(c * c.transpose())

131681894400

In [92]:
# 
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]
d = np.array(d)
d

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

In [90]:
# Exercise 1 - Find the sine of all the numbers in d

np.sin(d)


array([[ 0.70298154, -0.74125915,  0.68301051,  0.        ,  0.52143778,
        -0.65799923],
       [ 0.68301051, -0.70298154,  0.74125915, -0.17424404,  0.70298154,
         0.        ],
       [-0.29562771,  0.68301051, -0.68301051,  0.70298154, -0.68301051,
        -0.65799923]])

In [91]:
# Exercise 2 - Find the cosine of all the numbers in d
np.cos(d)


array([[0.71120809, 0.67121895, 0.73040855, 1.        , 0.85328931,
        0.7530186 ],
       [0.73040855, 0.71120809, 0.67121895, 0.9847025 , 0.71120809,
        1.        ],
       [0.95530323, 0.73040855, 0.73040855, 0.71120809, 0.73040855,
        0.7530186 ]])

In [93]:
# Exercise 3 - Find the tangent of all the numbers in d
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [99]:
# Exercise 4 - Find all the negative numbers in d
d[d < 0]

array([-90, -30, -45, -45])

In [101]:
# Exercise 5 - Find all the positive numbers in d
d[d > 0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [104]:
## Exercise 6 - Return an array of only the unique numbers in d.
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [105]:
# Exercise 7 - Determine how many unique numbers there are in d.
len(np.unique(d))

11

In [109]:
# Exercise 8 - Print out the shape of d.
d.shape

(3, 6)

In [111]:
# Exercise 9 - Transpose and then print out the shape of d.
np.transpose(d).shape

(6, 3)